title: Whiskey AI
description: Accelerating Food Fermentation and Beverage Ageing with Physics-Informed Edge AI to Reduce Environmental Impact

# permalink: pretty
remote_theme: "DigitaleGesellschaft/jekyll-theme-conference@v4.0.1"

# home: /
# copyright: Place Holder
# indexing: true

plugins:
  - jekyll-include-cache